
version: 2

sources:
    - name: Lead
      database: d7jmpjbun7g7bg
      schema: fa_r1_sf_lead
      loader: Stitch # information only (free text)
      # loader_at_field: field_name  use to calculate freshness

    - name: Opportunity
      database: d7jmpjbun7g7bg
      schema: fa_r1_sf_lead

      #freshness:
        #warm_after: {count: 24, period: hour}
models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: "lead_opp_fulljoin"
      description: "outer join between lead and opportunity"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
